namespace ZebraBarcodeScannerSDK;

public enum SDKResultCodes
{
    RESULT_SUCCESS,
    RESULT_FAILURE,
    SCANNER_NOT_AVAILABLE,
    RESULT_SCANNER_NOT_ACTIVE,
    RESULT_INVALID_PARAMS,
    RESULT_RESPONSE_TIMEOUT,
    RESULT_OPCODE_NOT_SUPPORTED,
    RESULT_SCANNER_ALREADY_ACTIVE,
    RESULT_FIRMWARE_UPDATE_IN_PROGRESS,
    RESULT_FIRMWARE_UPDATE_ABORTED,
    RESULT_SCALE_NOT_PRESENT,
}